configserver:
    name: configuration-server
    status: config-server running !!!  https://github.com/FrancoNeto/kaztor-dev 

jhipster:
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production
logging:
    file: ${java.io.tmpdir}/${spring.application.name}.log
