configserver:
    name: configuration-server
    status: config-server running !!!  https://github.com/FrancoNeto/kaztor-dev 

jhipster:
    security:
        authentication:
            jwt:
                secret: 1326cd01c410638616954b2e0e16cfb8cdddda7e
eureka:
    client:
        service-url:
            defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
