configserver:
    name: configuration-server
    status: running

jhipster:
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production

eureka:
    client:
        service-url:
            defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
