configserver:
    name: configuration-server
    status: config-server running !!!  https://github.com/FrancoNeto/kaztor-dev 

jhipster:
    cors:
        allowed-origins: "*"
        allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        allowed-headers: "*"
        exposed-headers: "Authorization, statusCode, statusKey"
        allow-credentials: true
        max-age: 1800
        
    security:
        authentication:
            jwt:
                secret: 15bc56e9ed2746b7805071831b5097cfd9e6db02

# Enable /management/logfile endpoint for all apps
logging:
    file: ${java.io.tmpdir}/${spring.application.name}.log
eureka:
    client:
        service-url:
            defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
