configserver:
    name: configuration-server
    status: running

jhipster:
    security:
        authentication:
            jwt:
                secret: teste-in-production


account:
        plan-1:
           deadline: 7
        plan-2:
           deadline: 30
        plan-3:
           deadline: 90
        plan-4:
           deadline: 180
